comment:
  layout: " diff, flags, files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
  hide_project_coverage: false
  status:
    project:
      default:   # default is the status check's name, not default settings
        target: auto 
        threshold: 1
        base: auto 
        flags: 
          - unit
